export const tokens = [
  "char",
  "class-name",
  "function",
  "mayble-class-name",
  "method",
  "function-variable",
  "variable",
  "attr-name",
  "punctuation",
  "operator",
  "markup",
  "tag",
  "atrule",
  "deleted",
  "selector",
  "string",
  "attr-value",
  "template-punctuation",
  "constant",
  "number",
  "builtin",
  "changed",
  "keyword",
  "interpolation-punctuation",
  "comment",
  "inserted",
  "prolog",
  new String(),
] as const;
